### ISSUE TITLE
Breaking changes in Ghost 0.10.0

### ISSUE THREAD

**Issue by kirrg001** [sanddudu/upyun-ghost-store#2]
Hey!

We will soon release Ghost `0.10.0` - in about 2 days.
It contains breaking changes for the storage adapter, see https://github.com/TryGhost/Ghost/wiki/Using-a-custom-storage-module.

**Comment by sanddudu** [comment]
@kirrg001 Thank you, I will push a new version as fast as I can.

**Comment by sanddudu** [comment]
@kirrg001 Are all these functions need to be functional? The module doesn't needs "exist" and "delete" functions.

**Comment by sanddudu** [comment]
@kirrg001 I have seen there are theme upload/download/delete functions in local storage module. Does that mean there 3rd-party storage module need to support these features too?

**Comment by sanddudu** [comment]
@kirrg001 By the way, the base class isn't necessary to my module too. If Ghost forced my modules to require that, users using this module and startup Ghost as a module will crash because they can't access Ghost core folder as usual (the location of contents folder is different than normal).

**Comment by sanddudu** [comment]
@kirrg001 One more question, how can I test my modules if it works properly on Ghost 0.10.0? Is the master branch has these breaking changes now?

**Comment by kirrg001** [comment]
You can test your storage adapter with the current master in Ghost. If you find any problems/bugs, we are very happy about a report.

All functions `exists`, `delete`, `save`, `serve` are required, but they can be just empty. We are planning to extend the usage of storage adapters. So in the near features, a custom storage adapter can be used to store images, themes and apps. 

Uploading themes is restricted in `0.10.0` to the `local-file-store`, so you don't have to change nothing except that your storage adapter passes the storage validation.

If you have more questions, can you please swing by our [slack channel](https://ghost.org/slack/)?Thanks :)

**Comment by sanddudu** [comment]
@kirrg001 Got it. Thanks for your answer.

**Comment by sanddudu** [comment]
Fixed
